spring:
  application:
    name: payment-service

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: W3C
  otlp:
    tracing:
      endpoint: http://alloy:4318/v1/traces

logging:
  structured:
    format:
      console: logstash
  level:
    root: INFO
    com.example.payment: DEBUG
